import { Level } from '@/types/content';

// Research brief (written for this app, general/adult audience, no
// invented statistics — grounded in established public-health guidance):
//
// What it is: alcohol is a central nervous system depressant. Moderate,
// social use is common; it becomes a problem when it's used to cope,
// escalates over time, or causes real harm to health, relationships, or
// responsibilities despite that harm being clear.
// Why it hooks: alcohol boosts dopamine and GABA activity, producing quick
// relaxation or euphoria. Regular use builds tolerance (more is needed for
// the same effect), and withdrawal symptoms (anxiety, poor sleep,
// irritability) reinforce continued use.
// Effects: impaired judgment and coordination even at low doses; heavy
// long-term use raises risk of liver disease, certain cancers, and
// cardiovascular problems, and commonly worsens anxiety and depression;
// alcohol can make falling asleep easier but reliably worsens sleep
// quality; it interacts dangerously with many medications.
// Triggers: stress, social pressure, celebration cues, boredom, using it
// to "unwind," being around others who are drinking.
// What helps: naming the actual need behind the urge (relaxation,
// socializing, escape) and finding another way to meet it; setting limits
// in advance; alternating alcoholic with non-alcoholic drinks; delaying
// the first drink; support from friends, family, or programs (AA, SMART
// Recovery, therapy). Anyone drinking heavily and regularly should not
// stop abruptly without medical guidance — withdrawal can be medically
// serious.

const categoryIds = ['alcohol'];
const cid = 'alc';

export const ALCOHOL_LEVELS: Level[] = [
  // ---------------------------------------------------------------- awareness
  {
    id: `${cid}_awareness_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 1,
    order: 1,
    type: 'documentation',
    title: 'Today’s Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A quick, honest look at today — no judgment.',
      fields: [
        { key: 'drinks', label: 'Roughly how many drinks today?', input: 'number' },
        { key: 'mood_after', label: 'Mood after drinking (or not drinking)', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you noticed?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_awareness_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 2,
    order: 2,
    type: 'lesson',
    title: 'What Alcohol Is Actually Doing',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Alcohol dampens the brain’s stress response for a short window, which is exactly why it can feel so relieving after a hard day. That relief is real but brief — and it’s exactly what makes it easy to start relying on.',
      questions: [
        {
          prompt: 'Why can a drink feel so relieving after a stressful day?',
          options: ['It permanently resolves the stress', 'It temporarily dampens the brain’s stress response', 'It has no measurable effect on stress'],
          correctIndex: 1,
          feedbackCorrect: 'Right — the relief is real but temporary, which is part of what makes it habit-forming.',
          feedbackIncorrect: 'Not quite — the effect is a temporary dampening, not a lasting fix.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 3,
    order: 3,
    type: 'exercise',
    title: 'Delay the First Drink',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Next time you reach for a drink out of habit rather than real choice, pause and breathe slowly through the timer before deciding.',
      format: 'breathing_timer',
      durationSeconds: 56,
      completionPrompt: 'Did you still want the drink after pausing, or did the urge shift?',
    },
  },
  {
    id: `${cid}_awareness_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 4,
    order: 4,
    type: 'lesson',
    title: 'Tolerance Creeps Up Quietly',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'The amount that once felt relaxing stops working the same way over time, often leading to drinking more just to get the same effect. Noticing that shift early — "I need more than I used to" — is worth paying attention to.',
      questions: [
        {
          prompt: 'What tends to happen with tolerance to alcohol over time?',
          options: ['The same amount keeps having the same effect', 'You need more to get the same effect', 'Tolerance has no real effect on drinking habits'],
          correctIndex: 1,
          feedbackCorrect: 'Right — rising tolerance is a real, worth-noticing pattern.',
          feedbackIncorrect: 'Actually, tolerance tends to rise, meaning more is needed for the same effect.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 5,
    order: 5,
    type: 'exercise',
    title: 'Notice Your Pattern',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think back over the past week. Write down which days you drank, roughly how much, and what was happening around those times.',
      format: 'real_world_task',
      durationSeconds: 120,
      completionPrompt: 'How clear is that pattern to you now, 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_awareness_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 6,
    order: 6,
    type: 'documentation',
    title: 'Awareness Check-Out',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You’ve spent this chapter just noticing, without trying to change anything yet.',
      fields: [
        { key: 'awareness_level', label: 'How aware of your drinking patterns do you feel now?', input: 'scale_1_5' },
        { key: 'biggest_surprise', label: 'What surprised you most this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ----------------------------------------------------------------- triggers
  {
    id: `${cid}_triggers_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 7,
    order: 7,
    type: 'documentation',
    title: 'When Do You Reach for It?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Think about the last few times you drank without really deciding to.',
      fields: [
        { key: 'moment', label: 'What was happening right before?', input: 'single_select', options: ['Stress from work', 'Social pressure', 'Celebrating', 'Boredom', 'Just "unwinding" out of habit'] },
        { key: 'notes', label: 'Anything else about the moment?', input: 'long_text' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_triggers_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 8,
    order: 8,
    type: 'lesson',
    title: 'Name the Real Need',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A drink is rarely about thirst — it’s usually standing in for relaxation, socializing, or escape from a feeling. Naming what you actually need in that moment makes it possible to find another way to meet it.',
      questions: [
        {
          prompt: 'What’s usually behind an urge to drink out of habit?',
          options: ['Pure physical thirst', 'A need like relaxation, socializing, or escaping a feeling', 'Nothing — it’s random'],
          correctIndex: 1,
          feedbackCorrect: 'Right — naming the real need is the first step to meeting it differently.',
          feedbackIncorrect: 'Not quite — habitual drinking is usually standing in for an emotional or social need.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 9,
    order: 9,
    type: 'exercise',
    title: 'Name Your Top Trigger',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'From this chapter’s check-in, pick the ONE trigger that shows up most for you. Write it down somewhere you’ll see it today.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How clear does that trigger feel to you now, 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_triggers_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 10,
    order: 10,
    type: 'lesson',
    title: 'Social Situations Without the Pressure',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A simple, confident line — "I’m driving" or "taking a break from it" — ends most conversations about not drinking quickly. Holding a drink, alcoholic or not, also removes a lot of the "why aren’t you drinking?" attention.',
      questions: [
        {
          prompt: 'What tends to reduce social pressure to drink?',
          options: ['A long explanation of your reasons', 'A short, confident line and holding a drink of some kind', 'Avoiding all social events forever'],
          correctIndex: 1,
          feedbackCorrect: 'Right — a short line and something in your hand usually does the trick.',
          feedbackIncorrect: 'Not quite — a brief, confident response tends to work better than a long explanation.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 11,
    order: 11,
    type: 'exercise',
    title: 'Prep Your Line',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Choose a go-to line for declining a drink, and a go-to non-alcoholic drink to hold instead. Practice saying the line out loud once.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How natural did it feel to say, 1 (awkward) to 5 (easy)?',
    },
  },
  {
    id: `${cid}_triggers_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 12,
    order: 12,
    type: 'documentation',
    title: 'Trigger Patterns Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now know more about what sets off your drinking than when you started.',
      fields: [
        { key: 'top_trigger', label: 'What’s your #1 trigger?', input: 'short_text' },
        { key: 'confidence', label: 'How confident do you feel spotting it in the moment?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------------- tools
  {
    id: `${cid}_tools_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 13,
    order: 13,
    type: 'documentation',
    title: 'What’s Worked So Far?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Before adding new tools, take stock of anything you’ve already tried.',
      fields: [
        { key: 'tried_before', label: 'Have you tried cutting back before? What happened?', input: 'long_text' },
        { key: 'openness', label: 'How open do you feel to trying something new?', input: 'scale_1_5' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_tools_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 14,
    order: 14,
    type: 'lesson',
    title: 'Set the Limit Before You Start',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Deciding how many drinks (or whether zero) before you’re in the moment is far more effective than deciding in the middle of a night out, when judgment is already affected by the first drink. A limit set in advance is a limit you can actually keep.',
      questions: [
        {
          prompt: 'When is the most effective time to decide your drink limit for the night?',
          options: ['After the first drink, once you’re more relaxed', 'Before you start drinking', 'It doesn’t matter when you decide'],
          correctIndex: 1,
          feedbackCorrect: 'Right — deciding in advance keeps the decision clear-headed.',
          feedbackIncorrect: 'Not quite — deciding before you start is far more reliable than deciding mid-way through.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 15,
    order: 15,
    type: 'exercise',
    title: 'Set Tonight’s Limit',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Before you’re in a drinking situation again, decide your limit for that occasion and write it down now, while you’re clear-headed.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How likely are you to stick to it, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 16,
    order: 16,
    type: 'lesson',
    title: 'Alternate as You Go',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Alternating an alcoholic drink with water or a non-alcoholic one slows your pace, keeps you hydrated, and gives you a natural point to reassess how you’re feeling before the next one.',
      questions: [
        {
          prompt: 'What’s a benefit of alternating alcoholic and non-alcoholic drinks?',
          options: ['It has no real effect on pacing', 'It slows your pace and gives you a natural check-in point', 'It only matters for how you feel the next morning'],
          correctIndex: 1,
          feedbackCorrect: 'Right — it naturally slows pacing and adds check-in moments.',
          feedbackIncorrect: 'Not quite — the main benefit is pacing and a natural pause to reassess.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 17,
    order: 17,
    type: 'exercise',
    title: 'Plan Your Next Occasion',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of your next upcoming social event. Write down how you’ll alternate drinks and what your limit will be.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How confident do you feel about this plan, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 18,
    order: 18,
    type: 'documentation',
    title: 'Tools Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now have a limit-setting habit and a pacing tool in place.',
      fields: [
        { key: 'sticking', label: 'Which tool has stuck so far?', input: 'short_text' },
        { key: 'effectiveness', label: 'How much has it helped?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------- reflection
  {
    id: `${cid}_reflection_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 19,
    order: 19,
    type: 'documentation',
    title: 'How’s It Going, Really?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'No pressure to be further along than you are — just be honest.',
      fields: [
        { key: 'progress_feeling', label: 'How do you feel about your progress?', input: 'scale_1_5' },
        { key: 'notes', label: 'What’s been hardest?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_reflection_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 20,
    order: 20,
    type: 'lesson',
    title: 'Alcohol and Sleep',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Alcohol can make it easier to fall asleep but reliably worsens sleep quality later in the night, fragmenting the deeper stages your body needs most. A night without it, even occasionally, is a real opportunity to notice the difference.',
      questions: [
        {
          prompt: 'What’s alcohol’s typical effect on sleep quality?',
          options: ['It reliably improves sleep quality all night', 'It can ease falling asleep but worsens quality later in the night', 'It has no measurable effect on sleep'],
          correctIndex: 1,
          feedbackCorrect: 'Right — the easier onset doesn’t translate to better overall sleep quality.',
          feedbackIncorrect: 'Not quite — alcohol tends to worsen sleep quality later in the night.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 21,
    order: 21,
    type: 'exercise',
    title: 'Notice How You Feel Tonight',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Tonight, whether or not you drink, take a few minutes before bed to notice how your body and mind feel — no comparison, just observation.',
      format: 'timed_reflection',
      durationSeconds: 90,
      completionPrompt: 'What did you notice?',
    },
  },
  {
    id: `${cid}_reflection_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 22,
    order: 22,
    type: 'lesson',
    title: 'A Hard Night Doesn’t Erase Progress',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A night where your limit didn’t hold doesn’t undo the awareness and tools you’ve already built. Guilt tends to make the next attempt harder, not easier — noticing what happened without judgment is what actually moves you forward.',
      questions: [
        {
          prompt: 'What tends to happen when guilt follows a night that didn’t go as planned?',
          options: ['It reliably makes the next attempt easier', 'It can make the next attempt harder, not easier', 'It has no real effect'],
          correctIndex: 1,
          feedbackCorrect: 'Right — guilt tends to work against you, not for you.',
          feedbackIncorrect: 'Actually, guilt tends to make the next attempt harder, not easier.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 23,
    order: 23,
    type: 'exercise',
    title: 'A Quick Self-Compassion Break',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of a recent night that didn’t go as planned. Silently say to yourself: "This is hard. Other people struggle with this too. I can be kind to myself and keep going."',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'How does it feel to offer yourself that kindness, 1 (strange) to 5 (genuinely comforting)?',
    },
  },
  {
    id: `${cid}_reflection_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 24,
    order: 24,
    type: 'documentation',
    title: 'Reflection Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A brief look at how your relationship with alcohol is shifting.',
      fields: [
        { key: 'self_kindness', label: 'How kind have you been to yourself this chapter?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you want to remember from this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ------------------------------------------------------------- maintenance
  {
    id: `${cid}_maintenance_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 25,
    order: 25,
    type: 'documentation',
    title: 'Where You Stand',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Almost through the path — a check-in before we talk about keeping it up long-term.',
      fields: [
        { key: 'change_noticed', label: 'What’s actually changed since you started?', input: 'long_text' },
        { key: 'confidence', label: 'How confident do you feel keeping this up?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_maintenance_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 26,
    order: 26,
    type: 'lesson',
    title: 'A Setback Isn’t a Restart',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A stressful week or a big social event can bring old drinking patterns back — that’s a normal bump in a long process, not proof it didn’t work. What matters most is noticing quickly and returning to your tools.',
      questions: [
        {
          prompt: 'If old drinking patterns return after weeks of progress, what does that mean?',
          options: ['Everything you built stopped mattering', 'It’s a normal bump — return to your tools quickly', 'You should give up on changing your drinking'],
          correctIndex: 1,
          feedbackCorrect: 'Right — getting back to your tools quickly matters far more than a perfect streak.',
          feedbackIncorrect: 'Not quite — a setback is normal and doesn’t erase what you’ve built.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 27,
    order: 27,
    type: 'exercise',
    title: 'Write Your Reset Plan',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down, in one sentence, what you’ll do the next time your limit doesn’t hold: which tool you’ll return to first, and who you might tell.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'Read your plan back — how ready do you feel to use it, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 28,
    order: 28,
    type: 'lesson',
    title: 'When to Get Real Support',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'If drinking is heavy and regular, stopping abruptly can be medically risky — withdrawal from alcohol can be serious and should be supervised by a doctor. Support groups like AA or SMART Recovery, therapy, and medical guidance all exist because this is genuinely hard to do entirely alone.',
      questions: [
        {
          prompt: 'Why shouldn’t someone who drinks heavily and regularly quit abruptly without medical guidance?',
          options: ['There’s no real risk either way', 'Withdrawal from heavy alcohol use can be medically serious', 'It only matters for people over 60'],
          correctIndex: 1,
          feedbackCorrect: 'Right — heavy, regular drinkers should get medical guidance before stopping abruptly.',
          feedbackIncorrect: 'Actually, abrupt withdrawal from heavy drinking can carry real medical risk.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 29,
    order: 29,
    type: 'exercise',
    title: 'Name Your Support Person',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of one person you could message if you wanted support around drinking. You can add them as an emergency contact in the SOS section if it feels right.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How comfortable would you feel reaching out to them, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 30,
    order: 30,
    type: 'documentation',
    title: 'Path Complete: Final Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You made it through the whole path. Take a moment to look back.',
      fields: [
        { key: 'proudest_moment', label: 'What are you most proud of from this path?', input: 'long_text' },
        { key: 'current_mood', label: 'How are you feeling right now?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
];
