import { Level } from '@/types/content';

// Research brief (spec §5.1): compulsive short-form scrolling runs on
// variable-reward psychology (same mechanic as slot machines), driven by
// boredom/loneliness/stress/FOMO, and costs sleep, mood, and attention.
// What helps: tracking use, adding friction, replacement habits, mindful
// use. Five chapters x six levels: awareness, triggers, tools, reflection,
// maintenance. Each chapter opens and closes on a Documentation check-in.

const categoryIds = ['doomscrolling'];
const cid = 'doom';

export const DOOMSCROLLING_LEVELS: Level[] = [
  // ---------------------------------------------------------------- awareness
  {
    id: `${cid}_awareness_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 1,
    order: 1,
    type: 'documentation',
    title: "Today's Scroll Check-In",
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'How much did you scroll today, and how did it leave you feeling?',
      fields: [
        { key: 'minutes', label: 'Minutes scrolled today (your best guess)', input: 'number' },
        { key: 'main_app', label: 'Main app', input: 'short_text' },
        { key: 'mood_after', label: 'Mood after scrolling', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you noticed?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_awareness_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 2,
    order: 2,
    type: 'lesson',
    title: 'The Slot-Machine Trick',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        "Short-form feeds run on ‘variable rewards.’ Sometimes the next clip is amazing, sometimes it's boring — and not knowing which is coming is exactly what keeps you pulling to refresh. It's the same design that makes slot machines hard to walk away from.",
      questions: [
        {
          prompt: 'Why is an endless feed so hard to put down?',
          options: [
            'Every clip is equally boring',
            'You never know if the next clip will be great, so you keep chasing it',
            'The app physically won’t let you close it',
          ],
          correctIndex: 1,
          feedbackCorrect: 'Exactly — the unpredictable payoff is what keeps you scrolling.',
          feedbackIncorrect: 'Not quite. It’s the *unpredictable* reward that keeps you going, not the content itself.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 3,
    order: 3,
    type: 'exercise',
    title: '3-Minute Reset',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction:
        'Put your phone face-down and out of reach. Look at one fixed object across the room for the full timer. Notice any tension in your neck, shoulders, or eyes — and let it soften on each exhale.',
      format: 'timed_reflection',
      durationSeconds: 180,
      completionPrompt: 'How does your body feel now compared to when you started?',
    },
  },
  {
    id: `${cid}_awareness_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 4,
    order: 4,
    type: 'lesson',
    title: 'What It’s Actually Costing You',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Heavy short-form use is linked to higher stress and anxiety, worse sleep from late-night blue light and stimulation, and a wired-but-tired feeling the next day. Physically, it adds up to more eye strain, neck and back tension, and hours of sitting still.',
      questions: [
        {
          prompt: 'Which of these is a documented effect of heavy short-form scrolling?',
          options: ['Improved deep sleep', 'Worse sleep and higher stress', 'No measurable effect on mood'],
          correctIndex: 1,
          feedbackCorrect: 'Right — sleep and mood are two of the most consistently affected areas.',
          feedbackIncorrect: 'Actually, heavy scrolling is linked to worse sleep and higher stress, not better outcomes.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 5,
    order: 5,
    type: 'exercise',
    title: 'One Honest Screen-Time Look',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction:
        'Open your phone’s screen-time or battery-usage settings and find yesterday’s total for your main short-form app. No judgment — just look at the real number.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How did seeing the real number feel — 1 (no surprise) to 5 (pretty surprising)?',
    },
  },
  {
    id: `${cid}_awareness_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 6,
    order: 6,
    type: 'documentation',
    title: 'Awareness Check-Out',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You’ve spent this chapter just noticing, without trying to change anything yet.',
      fields: [
        { key: 'awareness_level', label: 'How aware of your scrolling habits do you feel now?', input: 'scale_1_5' },
        { key: 'biggest_surprise', label: 'What surprised you most this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ----------------------------------------------------------------- triggers
  {
    id: `${cid}_triggers_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 7,
    order: 7,
    type: 'documentation',
    title: 'When Do You Reach for It?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Think about the last few times you opened the app without really deciding to.',
      fields: [
        { key: 'moment', label: 'What was happening right before?', input: 'single_select', options: ['Bored', 'Stressed', 'Lonely', 'Just woke up / about to sleep', 'Avoiding something else'] },
        { key: 'notes', label: 'Anything else about the moment?', input: 'long_text' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_triggers_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 8,
    order: 8,
    type: 'lesson',
    title: 'The Usual Suspects',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Most automatic scrolling traces back to a handful of repeat triggers: boredom, loneliness, stress, and social anxiety. The feed doesn’t create these feelings — it just offers a fast, low-effort escape from them, which is exactly why it’s so easy to reach for on autopilot.',
      questions: [
        {
          prompt: 'What role does the feed usually play when you’re bored or stressed?',
          options: ['It solves the underlying feeling', 'It offers a quick, low-effort escape from the feeling', 'It has no connection to how you feel'],
          correctIndex: 1,
          feedbackCorrect: 'Exactly — it’s an escape, not a fix, which is why the feeling is often still there after.',
          feedbackIncorrect: 'Not quite — scrolling tends to distract from a feeling temporarily, not resolve it.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 9,
    order: 9,
    type: 'exercise',
    title: 'Name Your Top Trigger',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'From this chapter’s check-ins, pick the ONE trigger that shows up most for you. Say it out loud, or write it down somewhere you’ll see it today.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How clear does that trigger feel to you now — 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_triggers_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 10,
    order: 10,
    type: 'lesson',
    title: 'FOMO Is by Design',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Feeds are built to make you feel like something important might happen if you stop watching — a new trend, a reply, a moment everyone else saw. That feeling is called FOMO, and it’s a reliable engagement driver, not a sign anything is actually urgent.',
      questions: [
        {
          prompt: 'FOMO while scrolling is best understood as:',
          options: ['A sign something urgent is happening', 'A designed feeling that keeps you engaged', 'Unrelated to app design'],
          correctIndex: 1,
          feedbackCorrect: 'Right — it’s a predictable design effect, not a reliable signal.',
          feedbackIncorrect: 'Actually, FOMO is a byproduct of how feeds are designed to keep you engaged.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 11,
    order: 11,
    type: 'exercise',
    title: 'Notice and Pause',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Next time you feel the urge to open the app, pause for the full timer before deciding. Just notice the urge — you don’t have to fight it, just watch it.',
      format: 'countdown',
      durationSeconds: 30,
      completionPrompt: 'Did the urge change at all during the pause — 1 (no change) to 5 (noticeably weaker)?',
    },
  },
  {
    id: `${cid}_triggers_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 12,
    order: 12,
    type: 'documentation',
    title: 'Trigger Patterns Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now know more about what sets off your scrolling than when you started.',
      fields: [
        { key: 'top_trigger', label: 'What’s your #1 trigger?', input: 'short_text' },
        { key: 'confidence', label: 'How confident do you feel spotting it in the moment?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------------- tools
  {
    id: `${cid}_tools_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 13,
    order: 13,
    type: 'documentation',
    title: 'What’s Worked So Far?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Before we add new tools, take stock of anything you’ve already tried.',
      fields: [
        { key: 'tried_before', label: 'Have you tried cutting back before? What happened?', input: 'long_text' },
        { key: 'openness', label: 'How open do you feel to trying something new?', input: 'scale_1_5' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_tools_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 14,
    order: 14,
    type: 'lesson',
    title: 'Friction Works',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Logging out after each use, moving the app off your home screen, or turning your phone to grayscale all add a few extra seconds before you can scroll. That small delay is often enough to turn an automatic open into an actual choice.',
      questions: [
        {
          prompt: 'What does adding "friction" to an app actually do?',
          options: ['Blocks the app completely', 'Adds a small delay that turns automatic use into a real choice', 'Makes the app load faster'],
          correctIndex: 1,
          feedbackCorrect: 'Exactly — it doesn’t remove the choice, it just slows down the automatic reflex.',
          feedbackIncorrect: 'Not quite — friction doesn’t block access, it just adds a pause before you act on autopilot.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 15,
    order: 15,
    type: 'exercise',
    title: 'Add One Friction Point',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Pick one: move your main short-form app off your home screen, log out of it, or turn on grayscale mode. Do it right now, before the timer runs out.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'Which friction point did you choose, and how easy was it to set up — 1 (hard) to 5 (easy)?',
    },
  },
  {
    id: `${cid}_tools_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 16,
    order: 16,
    type: 'lesson',
    title: 'Replace, Don’t Just Remove',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Willpower fades as the day goes on, so "just don’t scroll" rarely holds up by evening. Having a specific replacement ready — a book, a playlist, a two-minute call — for your exact trigger moments works far better than relying on discipline alone.',
      questions: [
        {
          prompt: 'Why is having a specific replacement activity more effective than just resisting?',
          options: ['Willpower is unlimited, so it doesn’t matter', 'Willpower fades through the day, so a ready plan works better', 'Replacements are only for beginners'],
          correctIndex: 1,
          feedbackCorrect: 'Right — a pre-decided replacement doesn’t depend on in-the-moment willpower.',
          feedbackIncorrect: 'Actually, willpower is a limited resource that fades — a plan beats relying on it alone.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 17,
    order: 17,
    type: 'exercise',
    title: 'Pick Your Go-To Swap',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Choose one replacement activity you’ll reach for instead of scrolling in your highest-risk moment (e.g. before bed). Try it right now for the length of the timer.',
      format: 'timed_reflection',
      durationSeconds: 120,
      completionPrompt: 'Could you see yourself using this swap again — 1 (no) to 5 (definitely)?',
    },
  },
  {
    id: `${cid}_tools_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 18,
    order: 18,
    type: 'documentation',
    title: 'Tools Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now have at least one friction point and one swap in place.',
      fields: [
        { key: 'sticking', label: 'Which tool has stuck so far?', input: 'short_text' },
        { key: 'effectiveness', label: 'How much has it helped?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------- reflection
  {
    id: `${cid}_reflection_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 19,
    order: 19,
    type: 'documentation',
    title: 'How’s It Going, Really?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'No pressure to be further along than you are — just be honest.',
      fields: [
        { key: 'progress_feeling', label: 'How do you feel about your progress?', input: 'scale_1_5' },
        { key: 'notes', label: 'What’s been hardest?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_reflection_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 20,
    order: 20,
    type: 'lesson',
    title: 'Mindful Use vs. Autopilot',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'The goal isn’t necessarily zero scrolling — it’s noticing when you’re doing it. Asking "how is this making me feel right now?" mid-scroll turns an automatic habit into a conscious choice, which is often enough to shorten the session on its own.',
      questions: [
        {
          prompt: 'What’s the core idea behind "mindful use"?',
          options: ['Never using the app again', 'Noticing how you feel while using it, instead of going on autopilot', 'Using it only for exactly 5 minutes a day'],
          correctIndex: 1,
          feedbackCorrect: 'Right — mindful use is about awareness in the moment, not a strict rule.',
          feedbackIncorrect: 'Not quite — mindful use is about noticing, not a hard time limit or total ban.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 21,
    order: 21,
    type: 'exercise',
    title: 'Mindful Scroll Check',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Open the app if you want to — but before you do, take three slow breaths and silently ask "how do I feel right now?" Notice the answer without judging it.',
      format: 'breathing_timer',
      durationSeconds: 45,
      completionPrompt: 'What did you notice about how you felt going in?',
    },
  },
  {
    id: `${cid}_reflection_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 22,
    order: 22,
    type: 'lesson',
    title: 'Be Kind About Slip-Ups',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A long scrolling session doesn’t erase your progress — shame just makes the next one more likely, because scrolling is also a way people cope with feeling bad about themselves. Noticing what happened and resetting beats a spiral of guilt every time.',
      questions: [
        {
          prompt: 'Why can shame after a long scroll session backfire?',
          options: ['It has no effect either way', 'It can trigger more scrolling as a way to cope with the bad feeling', 'It always prevents future scrolling'],
          correctIndex: 1,
          feedbackCorrect: 'Exactly — shame is often a trigger in itself, not a deterrent.',
          feedbackIncorrect: 'Actually, shame tends to feed the cycle rather than break it.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 23,
    order: 23,
    type: 'exercise',
    title: 'A Quick Self-Compassion Break',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of a recent moment you felt bad about scrolling too much. Silently say to yourself: "This is hard. Other people struggle with this too. I can be kind to myself and keep going."',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'How does it feel to offer yourself that kindness — 1 (strange) to 5 (genuinely comforting)?',
    },
  },
  {
    id: `${cid}_reflection_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 24,
    order: 24,
    type: 'documentation',
    title: 'Reflection Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A brief look at how your relationship with the habit is shifting.',
      fields: [
        { key: 'self_kindness', label: 'How kind have you been to yourself this chapter?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you want to remember from this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ------------------------------------------------------------- maintenance
  {
    id: `${cid}_maintenance_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 25,
    order: 25,
    type: 'documentation',
    title: 'Where You Stand',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Almost through the path — a check-in before we talk about keeping it up long-term.',
      fields: [
        { key: 'change_noticed', label: 'What’s actually changed since you started?', input: 'long_text' },
        { key: 'confidence', label: 'How confident do you feel keeping this up?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_maintenance_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 26,
    order: 26,
    type: 'lesson',
    title: 'Slipping Back Is Normal',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A stressful week or a bad night’s sleep can bring the old scrolling pattern right back — that’s a normal part of building any new habit, not proof it didn’t work. What matters most is how quickly you notice and reset, not whether it happens at all.',
      questions: [
        {
          prompt: 'If you slip back into heavy scrolling after weeks of progress, what does that mean?',
          options: ['The habit change failed completely', 'It’s a normal bump — what matters is resetting quickly', 'You should stop trying'],
          correctIndex: 1,
          feedbackCorrect: 'Right — a quick reset matters far more than a perfect streak.',
          feedbackIncorrect: 'Not quite — slips are a normal part of the process, not a sign of failure.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 27,
    order: 27,
    type: 'exercise',
    title: 'Write Your Reset Plan',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down, in one sentence, what you’ll do the next time you notice a scrolling slip: which friction point and which swap you’ll go back to first.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'Read your plan back — how ready do you feel to use it, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 28,
    order: 28,
    type: 'lesson',
    title: 'When to Loop In Someone Else',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'If scrolling is tangled up with ongoing low mood, isolation, or sleep problems that self-help tools aren’t touching, that’s worth mentioning to a trusted adult, friend, or a counselor. MAXX can support daily habits, but it isn’t a substitute for professional care when things feel bigger than a habit.',
      questions: [
        {
          prompt: 'When is it a good idea to talk to someone outside the app about your scrolling?',
          options: ['Only if you scroll every single day', 'If it’s tangled with ongoing low mood or sleep problems self-help isn’t fixing', 'Never — this is something to handle alone'],
          correctIndex: 1,
          feedbackCorrect: 'Exactly — that’s a good signal to bring in outside support.',
          feedbackIncorrect: 'Actually, that combination is a reasonable signal to loop in someone you trust.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 29,
    order: 29,
    type: 'exercise',
    title: 'Name Your Support Person',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of one person you could message if you wanted an accountability check-in about your screen time. You can add them as an emergency contact in the SOS section if it feels right.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How comfortable would you feel reaching out to them — 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 30,
    order: 30,
    type: 'documentation',
    title: 'Path Complete: Final Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You made it through the whole path. Take a moment to look back.',
      fields: [
        { key: 'proudest_moment', label: 'What are you most proud of from this path?', input: 'long_text' },
        { key: 'current_mood', label: 'How are you feeling right now?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
];
