import { Level } from '@/types/content';

// Research brief (written for this app, general/adult audience, no
// invented statistics — grounded in established public-health guidance):
//
// What it is: use of recreational or prescription substances beyond
// medical guidance or in ways that create real risk. A substance use
// disorder develops when use continues despite harm and becomes difficult
// to control on your own.
// Why it hooks: most misused substances act directly on the brain's reward
// circuitry, producing a faster, stronger dopamine surge than everyday
// rewards. Repeated use recalibrates that circuitry, making ordinary
// pleasures feel duller and cravings feel stronger over time.
// Effects: vary by substance, but commonly include impaired judgment,
// disrupted sleep, worsened anxiety or depression, physical health risks,
// and — for some substances — real physical dependence and withdrawal.
// Triggers: specific people, places, and routines tied to past use; stress
// and unresolved emotional pain; boredom; social settings where use is
// normalized.
// What helps: identifying and adjusting the people/places/routines tied to
// use; urge-surfing and grounding techniques; a real support network;
// professional support (therapy, medical supervision where relevant,
// structured programs like SMART Recovery or 12-step) combined with
// self-directed tools tends to outperform willpower alone. Stopping some
// substances abruptly (alcohol, benzodiazepines, opioids) can be
// medically risky and warrants professional guidance.

const categoryIds = ['drugs'];
const cid = 'drug';

export const DRUGS_LEVELS: Level[] = [
  // ---------------------------------------------------------------- awareness
  {
    id: `${cid}_awareness_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 1,
    order: 1,
    type: 'documentation',
    title: 'Today’s Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A quick, honest, private check-in.',
      fields: [
        { key: 'urge', label: 'How strong were your urges today?', input: 'scale_1_5' },
        { key: 'mood', label: 'How are you feeling overall?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you noticed?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_awareness_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 2,
    order: 2,
    type: 'lesson',
    title: 'Understanding Use, Not Judging It',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Substance use often starts as a way to manage stress, pain, boredom, or difficult emotions. Understanding what it’s doing for you is more useful than judging yourself for needing it — and it’s the starting point for finding something that works better.',
      questions: [
        {
          prompt: 'What’s usually more useful than self-judgment when looking at substance use?',
          options: ['Ignoring it completely', 'Understanding what need it’s meeting for you', 'Assuming it has no real cause'],
          correctIndex: 1,
          feedbackCorrect: 'Right — understanding the underlying need opens up better options.',
          feedbackIncorrect: 'Not quite — understanding the function it serves tends to be more useful than judgment.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 3,
    order: 3,
    type: 'exercise',
    title: 'Ground Yourself',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, and 1 you can taste. Take your time with each one.',
      format: 'timed_reflection',
      durationSeconds: 90,
      completionPrompt: 'How present and grounded do you feel now, 1 to 5?',
    },
  },
  {
    id: `${cid}_awareness_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 4,
    order: 4,
    type: 'lesson',
    title: 'What’s Happening in the Brain',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Most misused substances act directly on the brain’s reward circuitry, producing a faster, stronger dopamine surge than everyday rewards. Repeated use recalibrates that circuitry over time, which is part of why ordinary pleasures can start to feel duller.',
      questions: [
        {
          prompt: 'What can happen to the brain’s reward system with repeated substance use?',
          options: ['Nothing changes over time', 'It can recalibrate, making everyday rewards feel less satisfying', 'It only affects physical coordination'],
          correctIndex: 1,
          feedbackCorrect: 'Right — this recalibration is part of why cravings can feel stronger over time.',
          feedbackIncorrect: 'Not quite — repeated use can genuinely reshape how rewarding everyday things feel.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 5,
    order: 5,
    type: 'exercise',
    title: 'Notice Your Pattern',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think back over the last couple of weeks. Write down, privately, when use tends to happen — what time, what situation, what feeling comes right before.',
      format: 'real_world_task',
      durationSeconds: 120,
      completionPrompt: 'How clear is that pattern to you now, 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_awareness_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 6,
    order: 6,
    type: 'documentation',
    title: 'Awareness Check-Out',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You’ve spent this chapter just noticing, without trying to change anything yet.',
      fields: [
        { key: 'awareness_level', label: 'How aware of your patterns do you feel now?', input: 'scale_1_5' },
        { key: 'biggest_surprise', label: 'What surprised you most this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ----------------------------------------------------------------- triggers
  {
    id: `${cid}_triggers_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 7,
    order: 7,
    type: 'documentation',
    title: 'People, Places, and Things',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Think honestly about what tends to be tied to use for you.',
      fields: [
        { key: 'trigger_type', label: 'What tends to trigger it most?', input: 'single_select', options: ['Certain people', 'Certain places', 'Stress or emotional pain', 'Boredom', 'Social settings where it’s normalized'] },
        { key: 'notes', label: 'Anything else about it?', input: 'long_text' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_triggers_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 8,
    order: 8,
    type: 'lesson',
    title: 'Environment Shapes Behavior',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Certain people, places, and routines are strongly linked to use — not because they’re inherently dangerous, but because they’ve become associated with it over time. Identifying yours, without shame, makes it possible to plan around them.',
      questions: [
        {
          prompt: 'Why are certain people or places strongly linked to use?',
          options: ['They cause use directly no matter what', 'They’ve become associated with use through repetition', 'There’s no real connection'],
          correctIndex: 1,
          feedbackCorrect: 'Right — it’s a learned association, which means it can be worked with.',
          feedbackIncorrect: 'Not quite — the link is a learned association, not an inevitable cause.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 9,
    order: 9,
    type: 'exercise',
    title: 'Map Your Top Trigger',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'From this chapter’s check-in, pick the ONE person, place, or situation most tied to use for you. Write it down somewhere private.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How clear does that trigger feel to you now, 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_triggers_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 10,
    order: 10,
    type: 'lesson',
    title: 'Urge Surfing',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'An urge is like a wave — it rises, peaks, and falls, usually within a limited window, whether or not you act on it. "Urge surfing" means noticing the sensation in your body and riding it out, rather than fighting it or giving in immediately.',
      questions: [
        {
          prompt: 'What does "urge surfing" mean?',
          options: ['Fighting the urge as hard as possible', 'Noticing the urge and riding it out as it rises and falls', 'Giving in immediately to make it stop'],
          correctIndex: 1,
          feedbackCorrect: 'Right — riding it out tends to work better than fighting or giving in.',
          feedbackIncorrect: 'Not quite — urge surfing is about noticing and riding it out, not fighting or giving in.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 11,
    order: 11,
    type: 'exercise',
    title: 'Practice Urge Surfing',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Name where you feel an urge in your body right now, or recall a recent one. Breathe slowly through the timer and imagine it as a wave that will crest and fall.',
      format: 'breathing_timer',
      durationSeconds: 70,
      completionPrompt: 'How strong is the urge now compared to when you started, 1 (gone) to 5 (still strong)?',
    },
  },
  {
    id: `${cid}_triggers_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 12,
    order: 12,
    type: 'documentation',
    title: 'Trigger Patterns Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now know more about what sets off urges for you.',
      fields: [
        { key: 'top_trigger', label: 'What’s your #1 trigger?', input: 'short_text' },
        { key: 'confidence', label: 'How confident do you feel spotting it in the moment?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------------- tools
  {
    id: `${cid}_tools_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 13,
    order: 13,
    type: 'documentation',
    title: 'What’s Worked So Far?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Before adding new tools, take stock of anything you’ve already tried.',
      fields: [
        { key: 'tried_before', label: 'Have you tried cutting back or stopping before? What happened?', input: 'long_text' },
        { key: 'openness', label: 'How open do you feel to trying something new?', input: 'scale_1_5' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_tools_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 14,
    order: 14,
    type: 'lesson',
    title: 'Build a Support Bench',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Having two or three people you can reach out to in a hard moment — before you actually need them — makes a real difference. This app’s SOS feature can help you organize that list so it’s ready when you need it.',
      questions: [
        {
          prompt: 'When is the best time to identify your support people?',
          options: ['Only in the middle of a crisis', 'Before you need them, so the list is ready', 'It doesn’t really matter'],
          correctIndex: 1,
          feedbackCorrect: 'Right — having the list ready in advance makes it far more useful in a hard moment.',
          feedbackIncorrect: 'Not quite — building the list in advance is much more effective than scrambling in a crisis.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 15,
    order: 15,
    type: 'exercise',
    title: 'Add a Support Contact',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of one to two people you could reach out to in a hard moment. If it feels right, add them as an emergency contact in the SOS section.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How supported do you feel having this in place, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 16,
    order: 16,
    type: 'lesson',
    title: 'Professional Support Is a Strength',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Therapists, doctors, and support groups like SMART Recovery or 12-step programs exist because recovery is genuinely hard to do entirely alone. Using them is a sign of strategy, not a sign that self-directed tools have failed.',
      questions: [
        {
          prompt: 'What does using professional support usually indicate?',
          options: ['That self-help has completely failed', 'A strategic choice, since recovery is hard to do entirely alone', 'That the person isn’t trying hard enough'],
          correctIndex: 1,
          feedbackCorrect: 'Right — it’s a strategic addition, not an admission of failure.',
          feedbackIncorrect: 'Not quite — professional support is a strength, not a sign of failure.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 17,
    order: 17,
    type: 'exercise',
    title: 'Look Into One Resource',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Spend a few minutes looking up one resource — a therapist directory, SMART Recovery, or a local support group. You don’t have to contact them yet, just find one.',
      format: 'real_world_task',
      durationSeconds: 120,
      completionPrompt: 'Did you find something worth keeping for later, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 18,
    order: 18,
    type: 'documentation',
    title: 'Tools Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now have at least one support contact and maybe a resource in mind.',
      fields: [
        { key: 'sticking', label: 'Which tool has stuck so far?', input: 'short_text' },
        { key: 'effectiveness', label: 'How much has it helped?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------- reflection
  {
    id: `${cid}_reflection_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 19,
    order: 19,
    type: 'documentation',
    title: 'How’s It Going, Really?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'No pressure to be further along than you are — just be honest.',
      fields: [
        { key: 'progress_feeling', label: 'How do you feel about your progress?', input: 'scale_1_5' },
        { key: 'notes', label: 'What’s been hardest?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_reflection_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 20,
    order: 20,
    type: 'lesson',
    title: 'What the Substance Was Doing for You',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Understanding what a substance was actually giving you — numbing, connection, excitement, escape — makes it easier to find something else that meets that same need. Removing the substance without replacing what it provided tends not to last.',
      questions: [
        {
          prompt: 'Why does it help to understand what a substance was providing you?',
          options: ['It doesn’t matter once you’ve stopped', 'It helps you find another way to meet that same underlying need', 'It’s only useful for looking backward, not forward'],
          correctIndex: 1,
          feedbackCorrect: 'Right — replacing what it provided tends to last longer than removal alone.',
          feedbackIncorrect: 'Not quite — understanding the need helps you build something that actually replaces it.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 21,
    order: 21,
    type: 'exercise',
    title: 'Name What It Gave You',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Privately write down what the substance usually gave you — relief, connection, excitement, numbness — and one other way you could meet that same need this week.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How realistic does that alternative feel, 1 to 5?',
    },
  },
  {
    id: `${cid}_reflection_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 22,
    order: 22,
    type: 'lesson',
    title: 'A Slip Doesn’t Erase Progress',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Recovery rarely moves in a straight line, and a slip after progress doesn’t erase the awareness and tools you’ve already built. What matters most is what you do in the next hour — reaching out, resetting — not judging yourself for what already happened.',
      questions: [
        {
          prompt: 'What matters most after a slip during recovery?',
          options: ['Deciding recovery has failed', 'What you do in the next hour — reaching out and resetting', 'Ignoring it and hoping it won’t happen again'],
          correctIndex: 1,
          feedbackCorrect: 'Right — the next step matters more than the slip itself.',
          feedbackIncorrect: 'Not quite — what you do right after matters far more than the slip itself.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 23,
    order: 23,
    type: 'exercise',
    title: 'A Quick Self-Compassion Break',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of a recent hard moment. Silently say to yourself: "This is hard. Other people struggle with this too. I can be kind to myself and keep going."',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'How does it feel to offer yourself that kindness, 1 (strange) to 5 (genuinely comforting)?',
    },
  },
  {
    id: `${cid}_reflection_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 24,
    order: 24,
    type: 'documentation',
    title: 'Reflection Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A brief, private look at how things are shifting for you.',
      fields: [
        { key: 'self_kindness', label: 'How kind have you been to yourself this chapter?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you want to remember from this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ------------------------------------------------------------- maintenance
  {
    id: `${cid}_maintenance_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 25,
    order: 25,
    type: 'documentation',
    title: 'Where You Stand',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Almost through the path — a check-in before we talk about keeping it up long-term.',
      fields: [
        { key: 'change_noticed', label: 'What’s actually changed since you started?', input: 'long_text' },
        { key: 'confidence', label: 'How confident do you feel keeping this up?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_maintenance_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 26,
    order: 26,
    type: 'lesson',
    title: 'Watch for High-Risk Moments',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'The same people, places, and stressful moments that were triggers before can still be triggers after real progress — that’s not a sign the progress wasn’t real. Planning specifically for those known situations protects a streak far better than hoping willpower will be enough.',
      questions: [
        {
          prompt: 'Do old triggers still matter after weeks of progress?',
          options: ['No, they stop mattering entirely', 'Yes, planning for known high-risk situations still matters', 'Only if progress has been perfect so far'],
          correctIndex: 1,
          feedbackCorrect: 'Right — known triggers deserve a plan regardless of how much progress you’ve made.',
          feedbackIncorrect: 'Not quite — known triggers remain worth planning for, even after real progress.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 27,
    order: 27,
    type: 'exercise',
    title: 'Write Your Reset Plan',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down, in one sentence, what you’ll do the next time you’re in a high-risk situation: which tool you’ll use first, and who you’ll reach out to.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'Read your plan back — how ready do you feel to use it, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 28,
    order: 28,
    type: 'lesson',
    title: 'When to Get Medical Guidance',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Stopping some substances abruptly — including alcohol, benzodiazepines, and opioids — can be medically risky, so anyone who is a regular, heavy user should talk to a doctor before stopping suddenly. This app is a companion for daily habits, not a substitute for medical or professional care.',
      questions: [
        {
          prompt: 'Why might stopping a substance abruptly require medical guidance?',
          options: ['It never carries any real risk', 'For some substances, sudden withdrawal can be medically serious', 'Only illegal substances carry any withdrawal risk'],
          correctIndex: 1,
          feedbackCorrect: 'Right — some substances carry real withdrawal risk, which is why medical guidance matters.',
          feedbackIncorrect: 'Actually, sudden withdrawal from certain substances can be medically serious.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 29,
    order: 29,
    type: 'exercise',
    title: 'Confirm Your Support Bench',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Review your emergency contacts in the SOS section. Add or update anyone you’d want to reach out to if a high-risk moment came up.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How supported do you feel with this list in place, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 30,
    order: 30,
    type: 'documentation',
    title: 'Path Complete: Final Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You made it through the whole path. Take a moment to look back.',
      fields: [
        { key: 'proudest_moment', label: 'What are you most proud of from this path?', input: 'long_text' },
        { key: 'current_mood', label: 'How are you feeling right now?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
];
