import { Level } from '@/types/content';

// Research brief (spec §5.2): binge/emotional eating uses food to manage
// feelings rather than hunger; sugar and ultra-processed food spike dopamine
// fast; common triggers are stress, loneliness, boredom, all-or-nothing
// thinking. What helps: telling physical vs emotional hunger apart, urge
// surfing, non-food coping, regular structured meals, support.

const categoryIds = ['food'];
const cid = 'food';

export const FOOD_LEVELS: Level[] = [
  // ---------------------------------------------------------------- awareness
  {
    id: `${cid}_awareness_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 1,
    order: 1,
    type: 'documentation',
    title: 'Today’s Eating Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A quick, judgment-free look at how today went.',
      fields: [
        { key: 'mood', label: 'How do you feel about your eating today?', input: 'scale_1_5' },
        { key: 'craving', label: 'How strong were your cravings today?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you noticed?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_awareness_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 2,
    order: 2,
    type: 'lesson',
    title: 'Two Kinds of Hungry',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Physical hunger builds slowly and any food will do. Emotional hunger hits suddenly, usually alongside stress or boredom, and demands one specific comfort food. Learning to tell them apart is the first step to breaking the cycle.',
      questions: [
        {
          prompt: 'Which is a sign of emotional hunger?',
          options: ['It builds gradually over a couple of hours', 'A sudden, specific craving when you’re stressed', 'Your stomach is growling'],
          correctIndex: 1,
          feedbackCorrect: 'Right — emotional hunger is sudden and craving-specific.',
          feedbackIncorrect: 'Those describe physical hunger. Emotional hunger is sudden and specific.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 3,
    order: 3,
    type: 'exercise',
    title: 'The Hunger Pause',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Next time you want to eat outside of a regular meal, pause and ask: "Is this physical or emotional hunger?" Just notice the answer honestly — you don’t have to act on it yet.',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'Which kind of hunger did it turn out to be?',
    },
  },
  {
    id: `${cid}_awareness_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 4,
    order: 4,
    type: 'lesson',
    title: 'Why Sugar Hooks So Fast',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Sugary, highly processed foods spike dopamine quickly, which is exactly why they feel so satisfying in the moment. Regular use raises tolerance, meaning it takes more of that food to get the same lift — the same pattern behind most habit loops.',
      questions: [
        {
          prompt: 'What tends to happen with tolerance to highly processed food over time?',
          options: ['The same amount keeps feeling just as satisfying', 'You need more of it to get the same effect', 'Tolerance doesn’t apply to food'],
          correctIndex: 1,
          feedbackCorrect: 'Right — tolerance builds the same way it does with other habit loops.',
          feedbackIncorrect: 'Actually, tolerance builds over time, meaning more is needed for the same effect.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 5,
    order: 5,
    type: 'exercise',
    title: 'Notice Your Pattern',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think back over the last few days. Write down the time of day and situation when cravings tend to hit hardest for you.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How clear is that pattern to you now — 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_awareness_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 6,
    order: 6,
    type: 'documentation',
    title: 'Awareness Check-Out',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You’ve spent this chapter just noticing, without trying to change anything yet.',
      fields: [
        { key: 'awareness_level', label: 'How aware of your eating patterns do you feel now?', input: 'scale_1_5' },
        { key: 'biggest_surprise', label: 'What surprised you most this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ----------------------------------------------------------------- triggers
  {
    id: `${cid}_triggers_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 7,
    order: 7,
    type: 'documentation',
    title: 'What Sets It Off?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Think about the last time you ate past feeling full or reached for food you didn’t plan on.',
      fields: [
        { key: 'moment', label: 'What was happening right before?', input: 'single_select', options: ['Stress', 'Loneliness', 'Boredom', 'Home conflict', 'Eating in front of a screen'] },
        { key: 'notes', label: 'Anything else about the moment?', input: 'long_text' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_triggers_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 8,
    order: 8,
    type: 'lesson',
    title: 'Food as a Coping Tool',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Stress, loneliness, and boredom are three of the most common triggers behind eating that isn’t about hunger at all. Being alone with food, and eating while distracted by a screen, both make it easier to eat past the point of fullness without noticing.',
      questions: [
        {
          prompt: 'What do stress, loneliness, and boredom have in common as eating triggers?',
          options: ['They only affect people with no self-control', 'They’re common feelings food gets used to manage, not hunger signals', 'They have nothing to do with eating patterns'],
          correctIndex: 1,
          feedbackCorrect: 'Right — these are feelings, not hunger, and food becomes a way to cope with them.',
          feedbackIncorrect: 'Not quite — these are common emotional triggers, unrelated to actual hunger.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 9,
    order: 9,
    type: 'exercise',
    title: 'Ride the Wave',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Cravings are waves — they rise, peak, and fall, usually within 10-20 minutes, whether or not you act on them. Breathe slowly for the full timer and just let this one crest and pass.',
      format: 'breathing_timer',
      durationSeconds: 84,
      completionPrompt: 'How strong is the craving now compared to when you started, 1 (gone) to 5 (still strong)?',
    },
  },
  {
    id: `${cid}_triggers_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 10,
    order: 10,
    type: 'lesson',
    title: 'The All-or-Nothing Trap',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Strict "never again" rules tend to make a craving more intense when it hits, and one slip can trigger the thought "I already blew it, might as well keep going." Flexible, realistic goals hold up far better than perfection under pressure.',
      questions: [
        {
          prompt: 'What tends to make a craving more intense?',
          options: ['Riding it out for a few minutes', 'Strict, all-or-nothing restriction', 'Naming the craving out loud'],
          correctIndex: 1,
          feedbackCorrect: 'Right — strict restriction tends to backfire under pressure.',
          feedbackIncorrect: 'Not quite — all-or-nothing restriction is what tends to intensify cravings.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 11,
    order: 11,
    type: 'exercise',
    title: 'Rewrite the Rule',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Take one "never again" food rule you’ve set for yourself and rewrite it as something more flexible and realistic — something you could actually keep.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How much more doable does the new version feel, 1 to 5?',
    },
  },
  {
    id: `${cid}_triggers_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 12,
    order: 12,
    type: 'documentation',
    title: 'Trigger Patterns Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now know more about what sets off eating urges for you.',
      fields: [
        { key: 'top_trigger', label: 'What’s your #1 trigger?', input: 'short_text' },
        { key: 'confidence', label: 'How confident do you feel spotting it in the moment?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------------- tools
  {
    id: `${cid}_tools_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 13,
    order: 13,
    type: 'documentation',
    title: 'What’s Worked So Far?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Before adding new tools, take stock of anything you’ve already tried.',
      fields: [
        { key: 'tried_before', label: 'Have you tried changing your eating patterns before? What happened?', input: 'long_text' },
        { key: 'openness', label: 'How open do you feel to trying something new?', input: 'scale_1_5' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_tools_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 14,
    order: 14,
    type: 'lesson',
    title: 'Match the Craving, Not the Calories',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A crunchy craving isn’t solved by a soft "healthy" swap — matching texture and intensity works far better than matching calories. Sparkling water for a soda urge, roasted chickpeas for something salty and crunchy — swaps land when they actually feel similar.',
      questions: [
        {
          prompt: 'What makes a food swap more likely to actually satisfy a craving?',
          options: ['Matching the exact calorie count', 'Matching the texture and intensity of the craving', 'Choosing whatever is lowest in sugar'],
          correctIndex: 1,
          feedbackCorrect: 'Right — texture and intensity matter more than the numbers.',
          feedbackIncorrect: 'Not quite — matching texture and intensity tends to work better than matching calories.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 15,
    order: 15,
    type: 'exercise',
    title: 'Pick Your Go-To Swap',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Pick one swap that matches your most common craving (sweet, salty/crunchy, creamy, or fizzy), and write a one-line reminder to keep it stocked this week.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How likely are you to actually stock it this week, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 16,
    order: 16,
    type: 'lesson',
    title: 'Eat on a Rhythm',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Skipping meals sets up intense evening cravings, since your body compensates for missed energy later. Regular meals with protein keep blood sugar — and willpower — steadier through the day, which makes urges easier to ride out when they come.',
      questions: [
        {
          prompt: 'What’s a downside of skipping meals earlier in the day?',
          options: ['It has no effect on cravings later', 'It can set up more intense cravings in the evening', 'It permanently lowers your appetite'],
          correctIndex: 1,
          feedbackCorrect: 'Right — skipped meals often show up as stronger cravings later.',
          feedbackIncorrect: 'Actually, skipping meals tends to backfire as stronger cravings later in the day.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 17,
    order: 17,
    type: 'exercise',
    title: 'Plan Tomorrow’s Rhythm',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down three rough meal times for tomorrow, each with at least one source of protein. Keep it simple — this is a rhythm, not a strict diet.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How realistic does this plan feel, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 18,
    order: 18,
    type: 'documentation',
    title: 'Tools Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now have a go-to swap and a meal rhythm in place.',
      fields: [
        { key: 'sticking', label: 'Which tool has stuck so far?', input: 'short_text' },
        { key: 'effectiveness', label: 'How much has it helped?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------- reflection
  {
    id: `${cid}_reflection_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 19,
    order: 19,
    type: 'documentation',
    title: 'How’s It Going, Really?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'No pressure to be further along than you are — just be honest.',
      fields: [
        { key: 'progress_feeling', label: 'How do you feel about your progress?', input: 'scale_1_5' },
        { key: 'notes', label: 'What’s been hardest?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_reflection_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 20,
    order: 20,
    type: 'lesson',
    title: 'Eating Without a Screen',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Eating while distracted by a screen makes it much easier to miss your body’s fullness signals, so you keep going past the point you actually needed to stop. Even one meal a day eaten without a screen helps you reconnect with those signals.',
      questions: [
        {
          prompt: 'Why can eating in front of a screen lead to overeating?',
          options: ['Screens make food taste different', 'It’s easier to miss your body’s fullness signals while distracted', 'It has no real effect on eating'],
          correctIndex: 1,
          feedbackCorrect: 'Right — distraction makes it harder to notice you’re full.',
          feedbackIncorrect: 'Not quite — the issue is missing fullness cues while distracted, not taste.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 21,
    order: 21,
    type: 'exercise',
    title: 'One Screen-Free Bite',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Eat your next snack or meal with no phone, TV, or screen. Just notice the taste, texture, and how full you feel as you go.',
      format: 'timed_reflection',
      durationSeconds: 120,
      completionPrompt: 'What did you notice that you might normally miss?',
    },
  },
  {
    id: `${cid}_reflection_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 22,
    order: 22,
    type: 'lesson',
    title: 'Be Kind After a Binge',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Guilt and shame after eating more than intended often trigger more emotional eating, not less — the feeling itself becomes something to cope with. Noticing what happened without harsh self-judgment makes it far easier to get back to your rhythm the next meal.',
      questions: [
        {
          prompt: 'What tends to happen when shame follows a binge?',
          options: ['It reliably prevents the next one', 'It can trigger more emotional eating as a way to cope with the shame', 'It has no connection to future eating'],
          correctIndex: 1,
          feedbackCorrect: 'Right — shame often feeds the cycle instead of breaking it.',
          feedbackIncorrect: 'Actually, shame tends to feed the cycle rather than stop it.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 23,
    order: 23,
    type: 'exercise',
    title: 'A Quick Self-Compassion Break',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of a recent time you ate more than you meant to. Silently say to yourself: "This is hard. Other people struggle with this too. I can be kind to myself and get back on track."',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'How does it feel to offer yourself that kindness, 1 (strange) to 5 (genuinely comforting)?',
    },
  },
  {
    id: `${cid}_reflection_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 24,
    order: 24,
    type: 'documentation',
    title: 'Reflection Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A brief look at how your relationship with food is shifting.',
      fields: [
        { key: 'self_kindness', label: 'How kind have you been to yourself this chapter?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you want to remember from this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ------------------------------------------------------------- maintenance
  {
    id: `${cid}_maintenance_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 25,
    order: 25,
    type: 'documentation',
    title: 'Where You Stand',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Almost through the path — a check-in before we talk about keeping it up long-term.',
      fields: [
        { key: 'change_noticed', label: 'What’s actually changed since you started?', input: 'long_text' },
        { key: 'confidence', label: 'How confident do you feel keeping this up?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_maintenance_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 26,
    order: 26,
    type: 'lesson',
    title: 'A Hard Week Doesn’t Undo Progress',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'A stressful week or a skipped rhythm can bring old eating patterns back — that’s a normal part of change, not proof it didn’t work. What matters most is noticing quickly and returning to your tools, not maintaining a perfect streak.',
      questions: [
        {
          prompt: 'If old eating patterns show up again after weeks of progress, what does that mean?',
          options: ['The changes you made failed completely', 'It’s a normal bump — what matters is getting back to your tools', 'You should abandon your plan entirely'],
          correctIndex: 1,
          feedbackCorrect: 'Right — getting back to your tools matters far more than a perfect streak.',
          feedbackIncorrect: 'Not quite — a setback is a normal part of the process, not a sign of failure.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 27,
    order: 27,
    type: 'exercise',
    title: 'Write Your Reset Plan',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down, in one sentence, what you’ll do the next time you notice old eating patterns creeping back: which swap and which rhythm you’ll return to first.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'Read your plan back — how ready do you feel to use it, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 28,
    order: 28,
    type: 'lesson',
    title: 'When to Loop In Someone Else',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'If binge episodes are frequent, distressing, or paired with ongoing low mood or anxiety about your body, that’s worth bringing to a doctor or therapist. Support like this — alongside self-directed tools — tends to work better than trying to manage it entirely alone.',
      questions: [
        {
          prompt: 'When is it a good idea to get outside support for eating patterns?',
          options: ['Only if you’ve gained noticeable weight', 'If episodes are frequent, distressing, or tied to ongoing low mood', 'Never — this should be handled alone'],
          correctIndex: 1,
          feedbackCorrect: 'Right — that combination is a reasonable signal to get outside support.',
          feedbackIncorrect: 'Actually, frequent or distressing episodes are a good reason to loop in professional support.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 29,
    order: 29,
    type: 'exercise',
    title: 'Name Your Support Person',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of one person you could message if you wanted support around eating. You can add them as an emergency contact in the SOS section if it feels right.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How comfortable would you feel reaching out to them, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 30,
    order: 30,
    type: 'documentation',
    title: 'Path Complete: Final Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You made it through the whole path. Take a moment to look back.',
      fields: [
        { key: 'proudest_moment', label: 'What are you most proud of from this path?', input: 'long_text' },
        { key: 'current_mood', label: 'How are you feeling right now?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
];
