import { Level } from '@/types/content';

// Research brief (spec §5.4): smoking is both chemical dependence and a
// behavioral ritual; the body starts healing within minutes of the last
// cigarette; quitting usually takes several tries; alcohol and morning/
// after-meal cigarettes are common relapse triggers. What helps: physician
// advice + counseling + structured programs beat willpower alone.

const categoryIds = ['smoking'];
const cid = 'smoke';

export const SMOKING_LEVELS: Level[] = [
  // ---------------------------------------------------------------- awareness
  {
    id: `${cid}_awareness_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 1,
    order: 1,
    type: 'documentation',
    title: 'Today’s Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A quick, honest look at today — no judgment.',
      fields: [
        { key: 'cigarettes', label: 'Roughly how many today?', input: 'number' },
        { key: 'craving', label: 'How strong were your cravings today?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you noticed?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_awareness_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 2,
    order: 2,
    type: 'lesson',
    title: 'The Habit Behind the Habit',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Smoking is both a chemical dependence on nicotine and a behavioral ritual — the break, the hand-to-mouth motion, the exhale. Quitting well means addressing both, not just the craving for nicotine itself.',
      questions: [
        {
          prompt: 'Smoking is best understood as:',
          options: ['Only a chemical dependence', 'Only a behavioral ritual', 'Both a chemical dependence and a ritual'],
          correctIndex: 2,
          feedbackCorrect: 'Right — both parts need a plan, not just the craving itself.',
          feedbackIncorrect: 'Actually, it’s both — the chemical craving and the ritual around it.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 3,
    order: 3,
    type: 'exercise',
    title: 'Replace the Ritual',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Step outside or away from your desk, just like a smoke break — minus the cigarette. Take slow, deliberate breaths for the full timer, like a long drag and exhale.',
      format: 'breathing_timer',
      durationSeconds: 78,
      completionPrompt: 'How did doing the ritual without the cigarette feel?',
    },
  },
  {
    id: `${cid}_awareness_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 4,
    order: 4,
    type: 'lesson',
    title: 'Your Body Starts Healing Fast',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Within 20 minutes of a last cigarette, heart rate starts to drop. Within 12 hours, carbon monoxide levels in the blood return to normal. The payoff of cutting back or quitting starts almost immediately, long before any long-term risk changes.',
      questions: [
        {
          prompt: 'How soon does the body start showing benefits after the last cigarette?',
          options: ['Within minutes to hours', 'Only after several years', 'There’s no measurable early benefit'],
          correctIndex: 0,
          feedbackCorrect: 'Right — heart rate and carbon monoxide levels improve within hours.',
          feedbackIncorrect: 'Actually, measurable benefits start within minutes to hours, not years.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 5,
    order: 5,
    type: 'exercise',
    title: 'Notice Your Pattern',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think back over today. Write down the exact moments you smoked — what time, what you were doing right before.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How clear is that pattern to you now, 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_awareness_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 6,
    order: 6,
    type: 'documentation',
    title: 'Awareness Check-Out',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You’ve spent this chapter just noticing, without trying to change anything yet.',
      fields: [
        { key: 'awareness_level', label: 'How aware of your smoking patterns do you feel now?', input: 'scale_1_5' },
        { key: 'biggest_surprise', label: 'What surprised you most this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ----------------------------------------------------------------- triggers
  {
    id: `${cid}_triggers_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 7,
    order: 7,
    type: 'documentation',
    title: 'Your Riskiest Moments',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Think about which moments feel hardest to get through without a cigarette.',
      fields: [
        { key: 'moment', label: 'What’s your highest-risk moment?', input: 'single_select', options: ['First thing in the morning', 'Right after a meal', 'With coffee', 'When drinking alcohol', 'Stressful moments'] },
        { key: 'notes', label: 'Anything else about it?', input: 'long_text' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_triggers_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 8,
    order: 8,
    type: 'lesson',
    title: 'Mornings and After Meals',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'For most smokers, the first cigarette of the day and the one after eating are the most automatic — they’re tied tightly to routine, not necessarily the strongest craving. Planning a specific alternative for exactly these two moments has an outsized effect.',
      questions: [
        {
          prompt: 'Why are the first cigarette of the day and the after-meal one worth special attention?',
          options: ['They’re the least automatic ones', 'They’re the most automatic, routine-tied moments', 'They don’t matter more than any other cigarette'],
          correctIndex: 1,
          feedbackCorrect: 'Right — these routine-tied moments are worth planning for specifically.',
          feedbackIncorrect: 'Not quite — these two moments tend to be the most automatic and routine-driven.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 9,
    order: 9,
    type: 'exercise',
    title: 'Plan Your Riskiest Moment',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Pick your single riskiest moment (morning, after a meal, with coffee) and decide right now what you’ll do instead next time — brush your teeth, go for a short walk, chew gum.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How ready do you feel to use that plan, 1 to 5?',
    },
  },
  {
    id: `${cid}_triggers_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 10,
    order: 10,
    type: 'lesson',
    title: 'Alcohol Lowers Your Guard',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Drinking is one of the most common relapse triggers for people cutting back on smoking — it lowers inhibition right when you need your plan the most. If you’re early in cutting back, consider drinking less too, at least for a few weeks.',
      questions: [
        {
          prompt: 'Why is drinking alcohol a common relapse trigger for smoking?',
          options: ['Alcohol has no connection to smoking', 'It lowers inhibition, making it easier to abandon your plan', 'It only affects heavy drinkers'],
          correctIndex: 1,
          feedbackCorrect: 'Right — lowered inhibition makes it easier to slip back into old patterns.',
          feedbackIncorrect: 'Not quite — alcohol’s effect on inhibition is exactly what makes it a common trigger.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 11,
    order: 11,
    type: 'exercise',
    title: 'Delay, Don’t Deny',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Instead of "never again," try "not for the next few minutes." When a craving hits, set the timer and just wait it out — no other rule attached.',
      format: 'countdown',
      durationSeconds: 180,
      completionPrompt: 'Did the urge change while you waited, 1 (no change) to 5 (noticeably weaker)?',
    },
  },
  {
    id: `${cid}_triggers_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 12,
    order: 12,
    type: 'documentation',
    title: 'Trigger Patterns Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now know more about what sets off your smoking than when you started.',
      fields: [
        { key: 'top_trigger', label: 'What’s your #1 trigger?', input: 'short_text' },
        { key: 'confidence', label: 'How confident do you feel spotting it in the moment?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------------- tools
  {
    id: `${cid}_tools_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 13,
    order: 13,
    type: 'documentation',
    title: 'What’s Worked So Far?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Before adding new tools, take stock of anything you’ve already tried.',
      fields: [
        { key: 'tried_before', label: 'Have you tried quitting or cutting back before? What happened?', input: 'long_text' },
        { key: 'openness', label: 'How open do you feel to trying something new?', input: 'scale_1_5' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_tools_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 14,
    order: 14,
    type: 'lesson',
    title: 'Most Quits Take a Few Tries',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Relapse is common when quitting smoking and doesn’t mean you failed — it means you’re learning your specific triggers. Each attempt tends to make the next one more informed, especially when you actually change your approach based on what happened.',
      questions: [
        {
          prompt: 'What does a relapse while quitting smoking usually mean?',
          options: ['You’ll never be able to quit', 'You’re learning your triggers, which helps the next attempt', 'You should stop trying entirely'],
          correctIndex: 1,
          feedbackCorrect: 'Right — most people who quit successfully needed more than one attempt.',
          feedbackIncorrect: 'Not quite — a relapse is common and usually informs a stronger next attempt.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 15,
    order: 15,
    type: 'exercise',
    title: 'What Will You Hold Instead?',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Pick something to hold or use instead of a cigarette during your break — a pen, a stress ball, a cup of tea. Try it right now for the length of the timer.',
      format: 'timed_reflection',
      durationSeconds: 120,
      completionPrompt: 'Could you see yourself using this again, 1 (no) to 5 (definitely)?',
    },
  },
  {
    id: `${cid}_tools_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 16,
    order: 16,
    type: 'lesson',
    title: 'Support Beats Willpower Alone',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Physician advice, counseling, and structured quit programs consistently outperform trying to quit through willpower alone. Combining a real plan with outside support — even briefly — meaningfully raises the odds of it sticking.',
      questions: [
        {
          prompt: 'What does the evidence say improves the odds of quitting successfully?',
          options: ['Willpower alone works best', 'Combining a plan with physician advice, counseling, or a program', 'Nothing meaningfully changes the odds'],
          correctIndex: 1,
          feedbackCorrect: 'Right — structured support consistently beats willpower alone.',
          feedbackIncorrect: 'Actually, combining a plan with real support tends to work far better than willpower alone.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 17,
    order: 17,
    type: 'exercise',
    title: 'Look Into One Resource',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Spend a few minutes looking up one quit-smoking resource — a hotline, an app, or your doctor’s advice line. You don’t have to call yet, just find it.',
      format: 'real_world_task',
      durationSeconds: 120,
      completionPrompt: 'Did you find something worth keeping for later, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 18,
    order: 18,
    type: 'documentation',
    title: 'Tools Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now have a replacement ritual and maybe a resource in mind.',
      fields: [
        { key: 'sticking', label: 'Which tool has stuck so far?', input: 'short_text' },
        { key: 'effectiveness', label: 'How much has it helped?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------- reflection
  {
    id: `${cid}_reflection_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 19,
    order: 19,
    type: 'documentation',
    title: 'How’s It Going, Really?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'No pressure to be further along than you are — just be honest.',
      fields: [
        { key: 'progress_feeling', label: 'How do you feel about your progress?', input: 'scale_1_5' },
        { key: 'notes', label: 'What’s been hardest?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_reflection_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 20,
    order: 20,
    type: 'lesson',
    title: 'Notice the Craving, Don’t Fight It',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Fighting a craving head-on often makes it feel bigger. Simply noticing it — "there’s that urge again" — without judgment tends to let it pass faster than trying to white-knuckle through it.',
      questions: [
        {
          prompt: 'What tends to happen when you fight a craving head-on?',
          options: ['It reliably disappears faster', 'It can feel bigger and harder to manage', 'It has no effect either way'],
          correctIndex: 1,
          feedbackCorrect: 'Right — fighting it directly often makes it feel more intense.',
          feedbackIncorrect: 'Not quite — fighting a craving directly tends to make it feel stronger, not weaker.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 21,
    order: 21,
    type: 'exercise',
    title: 'Just Notice It',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'If you feel a craving right now, don’t try to push it away. Just silently name it — "there’s the urge" — and breathe through the full timer.',
      format: 'breathing_timer',
      durationSeconds: 42,
      completionPrompt: 'What did you notice about the craving as you watched it?',
    },
  },
  {
    id: `${cid}_reflection_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 22,
    order: 22,
    type: 'lesson',
    title: 'A Slip Doesn’t Erase Progress',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Smoking again after days or weeks without doesn’t undo the healing your body already started, and it doesn’t mean you have to start completely over. Getting back to your plan quickly matters far more than never slipping at all.',
      questions: [
        {
          prompt: 'If you smoke again after weeks of progress, what does that mean for your body?',
          options: ['All the healing that happened is reversed instantly', 'The progress your body made doesn’t just disappear', 'You have to start counting from zero physically'],
          correctIndex: 1,
          feedbackCorrect: 'Right — a slip doesn’t erase the healing that already happened.',
          feedbackIncorrect: 'Not quite — your body’s progress doesn’t simply reverse from one slip.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 23,
    order: 23,
    type: 'exercise',
    title: 'A Quick Self-Compassion Break',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of a recent slip or hard moment. Silently say to yourself: "This is hard. Other people struggle with this too. I can be kind to myself and keep going."',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'How does it feel to offer yourself that kindness, 1 (strange) to 5 (genuinely comforting)?',
    },
  },
  {
    id: `${cid}_reflection_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 24,
    order: 24,
    type: 'documentation',
    title: 'Reflection Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A brief look at how your relationship with smoking is shifting.',
      fields: [
        { key: 'self_kindness', label: 'How kind have you been to yourself this chapter?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you want to remember from this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ------------------------------------------------------------- maintenance
  {
    id: `${cid}_maintenance_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 25,
    order: 25,
    type: 'documentation',
    title: 'Where You Stand',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Almost through the path — a check-in before we talk about keeping it up long-term.',
      fields: [
        { key: 'change_noticed', label: 'What’s actually changed since you started?', input: 'long_text' },
        { key: 'confidence', label: 'How confident do you feel keeping this up?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_maintenance_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 26,
    order: 26,
    type: 'lesson',
    title: 'Cutting Back Helps at Any Age',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Quitting smoking lowers cancer, heart, and stroke risk at any age — the benefit is bigger the earlier it happens, but it’s never zero. That’s true whether this is your first attempt or your fifth.',
      questions: [
        {
          prompt: 'Does quitting smoking still help if you’ve smoked for a long time?',
          options: ['No, the damage is already done either way', 'Yes — risk drops at any age, though earlier is better', 'Only if you quit before age 20'],
          correctIndex: 1,
          feedbackCorrect: 'Right — there’s a real benefit at any age, not just early on.',
          feedbackIncorrect: 'Actually, quitting lowers risk at any age, even later in life.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 27,
    order: 27,
    type: 'exercise',
    title: 'Write Your Reset Plan',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down, in one sentence, what you’ll do the next time a craving hits hard: your replacement ritual and who you’ll reach out to if needed.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'Read your plan back — how ready do you feel to use it, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 28,
    order: 28,
    type: 'lesson',
    title: 'When to Loop In a Professional',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'If cravings feel unmanageable, or quitting is tangled up with stress or mood you can’t get ahead of alone, a doctor or a structured cessation program can offer medical options and support this app can’t. That’s a sign of strategy, not failure.',
      questions: [
        {
          prompt: 'When is it worth talking to a doctor about quitting smoking?',
          options: ['Only after you’ve completely quit on your own', 'If cravings feel unmanageable or are tangled with mood you can’t handle alone', 'Never — self-help tools are always enough'],
          correctIndex: 1,
          feedbackCorrect: 'Right — that’s exactly when professional support adds real value.',
          feedbackIncorrect: 'Actually, that’s a reasonable moment to bring in professional support.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 29,
    order: 29,
    type: 'exercise',
    title: 'Name Your Support Person',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of one person you could message if a craving felt like too much to handle alone. You can add them as an emergency contact in the SOS section if it feels right.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How comfortable would you feel reaching out to them, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 30,
    order: 30,
    type: 'documentation',
    title: 'Path Complete: Final Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You made it through the whole path. Take a moment to look back.',
      fields: [
        { key: 'proudest_moment', label: 'What are you most proud of from this path?', input: 'long_text' },
        { key: 'current_mood', label: 'How are you feeling right now?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
];
