import { Level } from '@/types/content';

// Research brief (spec §5.3): vaping delivers nicotine, which is highly
// addictive and reshapes reward/impulse circuitry; aerosol carries real
// chemical exposure; triggers are situational (after meals, stress, driving,
// drinking, boredom). What helps: counseling/behavioral strategies (not just
// switching devices), environment changes, telling someone.

const categoryIds = ['vaping'];
const cid = 'vape';

export const VAPING_LEVELS: Level[] = [
  // ---------------------------------------------------------------- awareness
  {
    id: `${cid}_awareness_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 1,
    order: 1,
    type: 'documentation',
    title: 'Today’s Vape Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A quick, honest look at today — no judgment.',
      fields: [
        { key: 'puffs_estimate', label: 'Rough sense of how much you vaped today', input: 'single_select', options: ['A lot more than usual', 'About usual', 'Less than usual', 'None'] },
        { key: 'craving', label: 'How strong were your cravings today?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you noticed?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_awareness_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 2,
    order: 2,
    type: 'lesson',
    title: 'What Nicotine Is Actually Doing',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Vaped nicotine reaches your brain in seconds, which is part of why it can feel so needed in stressful moments — and why irritability and restlessness can show up quickly when you go without it. Craving it isn’t a sign of weak willpower; it’s your body reacting to a substance built to be habit-forming.',
      questions: [
        {
          prompt: 'Why does a nicotine craving feel so urgent?',
          options: ['Nicotine has no real effect on the brain', 'Nicotine reaches the brain fast, creating a strong, quick habit loop', 'It’s purely a matter of personal willpower'],
          correctIndex: 1,
          feedbackCorrect: 'Right — the speed of the hit is exactly what makes it so habit-forming.',
          feedbackIncorrect: 'Not quite — the fast brain effect is what drives the strong urge, not a willpower issue.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 3,
    order: 3,
    type: 'exercise',
    title: 'The 4-Minute Reset',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Most nicotine cravings peak and fade within a few minutes. Breathe slowly through the full timer — box breathing, in for 4, hold for 4, out for 4 — and just let this one pass.',
      format: 'breathing_timer',
      durationSeconds: 72,
      completionPrompt: 'How strong is the craving now compared to when you started, 1 (gone) to 5 (still strong)?',
    },
  },
  {
    id: `${cid}_awareness_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 4,
    order: 4,
    type: 'lesson',
    title: 'What’s in the Aerosol',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        '"It’s just vapor" is a myth — vape aerosol can contain formaldehyde, benzene, and heavy metals alongside nicotine and flavoring chemicals. It’s linked to cough, wheezing, and worsened asthma, and nicotine itself raises heart rate and blood pressure.',
      questions: [
        {
          prompt: 'Is vape aerosol accurately described as "just water vapor"?',
          options: ['Yes, it’s harmless water vapor', 'No, it can contain formaldehyde, benzene, and heavy metals', 'Only cheap vape brands contain anything harmful'],
          correctIndex: 1,
          feedbackCorrect: 'Right — "just vapor" is a myth; real chemical exposure is involved.',
          feedbackIncorrect: 'Actually, vape aerosol can carry real chemical exposure, not just water vapor.',
        },
      ],
    },
  },
  {
    id: `${cid}_awareness_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 5,
    order: 5,
    type: 'exercise',
    title: 'Count Today’s Reaches',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'For the rest of today, notice each time you reach for your vape without really deciding to. You don’t have to stop — just count and notice.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How automatic did most of those reaches feel, 1 (very deliberate) to 5 (totally automatic)?',
    },
  },
  {
    id: `${cid}_awareness_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'awareness',
    levelNumber: 6,
    order: 6,
    type: 'documentation',
    title: 'Awareness Check-Out',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You’ve spent this chapter just noticing, without trying to change anything yet.',
      fields: [
        { key: 'awareness_level', label: 'How aware of your vaping patterns do you feel now?', input: 'scale_1_5' },
        { key: 'biggest_surprise', label: 'What surprised you most this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ----------------------------------------------------------------- triggers
  {
    id: `${cid}_triggers_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 7,
    order: 7,
    type: 'documentation',
    title: 'When Do You Reach for It?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Think about the last few times you vaped without really deciding to.',
      fields: [
        { key: 'moment', label: 'What was happening right before?', input: 'single_select', options: ['After a meal', 'Stressed', 'Driving', 'Drinking alcohol', 'Bored / idle hands'] },
        { key: 'notes', label: 'Anything else about the moment?', input: 'long_text' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_triggers_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 8,
    order: 8,
    type: 'lesson',
    title: 'Triggers Are Predictable',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Most vaping happens around a handful of repeat cues: after meals, during stress, while driving, drinking, or feeling bored. Naming yours in advance makes them far easier to catch in the moment, instead of noticing only after you’ve already reached for it.',
      questions: [
        {
          prompt: 'Why is it useful to name your vaping triggers in advance?',
          options: ['It guarantees you’ll never vape again', 'It makes the moment easier to catch before you act on autopilot', 'It has no practical use'],
          correctIndex: 1,
          feedbackCorrect: 'Right — naming a trigger in advance helps you catch it in the moment.',
          feedbackIncorrect: 'Not quite — the value is catching the moment earlier, not a guarantee.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 9,
    order: 9,
    type: 'exercise',
    title: 'Map Your Top Trigger',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'From this chapter’s check-in, pick the ONE trigger that shows up most for you. Write it down somewhere you’ll see it today.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How clear does that trigger feel to you now, 1 (fuzzy) to 5 (very clear)?',
    },
  },
  {
    id: `${cid}_triggers_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 10,
    order: 10,
    type: 'lesson',
    title: 'Environment Shapes Behavior',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Removing your vape from your car, desk, or pocket adds a real decision point — if it takes more than a few seconds to get one, that pause matters. Small environment changes are often more reliable than willpower alone in the moment.',
      questions: [
        {
          prompt: 'What’s the benefit of keeping your vape somewhere less convenient?',
          options: ['It has no real effect', 'It adds a decision point that can interrupt automatic use', 'It only helps if you throw it away completely'],
          correctIndex: 1,
          feedbackCorrect: 'Right — small friction points create a real pause to decide.',
          feedbackIncorrect: 'Not quite — the value comes from a small added decision point, not needing to throw it away.',
        },
      ],
    },
  },
  {
    id: `${cid}_triggers_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 11,
    order: 11,
    type: 'exercise',
    title: 'One Environment Change',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Pick one place your vape usually lives (car, desk, pocket) and move it somewhere less convenient right now.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How much friction did that add, 1 (barely any) to 5 (a real pause)?',
    },
  },
  {
    id: `${cid}_triggers_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'triggers',
    levelNumber: 12,
    order: 12,
    type: 'documentation',
    title: 'Trigger Patterns Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now know more about what sets off your vaping than when you started.',
      fields: [
        { key: 'top_trigger', label: 'What’s your #1 trigger?', input: 'short_text' },
        { key: 'confidence', label: 'How confident do you feel spotting it in the moment?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------------- tools
  {
    id: `${cid}_tools_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 13,
    order: 13,
    type: 'documentation',
    title: 'What’s Worked So Far?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Before adding new tools, take stock of anything you’ve already tried.',
      fields: [
        { key: 'tried_before', label: 'Have you tried cutting back before? What happened?', input: 'long_text' },
        { key: 'openness', label: 'How open do you feel to trying something new?', input: 'scale_1_5' },
      ],
      shareableToCommunity: false,
    },
  },
  {
    id: `${cid}_tools_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 14,
    order: 14,
    type: 'lesson',
    title: 'Give Your Hands Something to Do',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Part of the vaping habit is physical — the hand-to-mouth motion, the fidgeting. Chewing gum, holding a cold water bottle, or squeezing a stress ball gives your hands and mouth something to do during a craving without needing the device.',
      questions: [
        {
          prompt: 'Why can a simple hand/mouth substitute (gum, a stress ball) help with cravings?',
          options: ['It has no real effect', 'Part of the habit is physical, and it gives that part something else to do', 'It only works for people who chew gum regularly'],
          correctIndex: 1,
          feedbackCorrect: 'Right — the physical ritual is part of the habit, and substitutes address that directly.',
          feedbackIncorrect: 'Not quite — the physical, hand-to-mouth part of the habit is real and worth addressing.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 15,
    order: 15,
    type: 'exercise',
    title: 'Pick Your Hand Substitute',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Choose one substitute for your hands and mouth during a craving — gum, a cold water bottle, a stress ball, a straw — and keep it within reach for the rest of today.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How likely are you to actually reach for it next time, 1 to 5?',
    },
  },
  {
    id: `${cid}_tools_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 16,
    order: 16,
    type: 'lesson',
    title: 'Telling Someone Helps',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'People who tell at least one other person they’re cutting back are more likely to actually follow through — accountability plus support beats willpower alone. It doesn’t have to be a big conversation, just one honest sentence to someone you trust.',
      questions: [
        {
          prompt: 'What tends to improve someone’s odds of following through on cutting back?',
          options: ['Keeping it completely private', 'Telling at least one other person for accountability', 'Only relying on personal willpower'],
          correctIndex: 1,
          feedbackCorrect: 'Right — accountability and support tend to outperform willpower alone.',
          feedbackIncorrect: 'Actually, telling someone tends to improve follow-through more than going it alone.',
        },
      ],
    },
  },
  {
    id: `${cid}_tools_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 17,
    order: 17,
    type: 'exercise',
    title: 'Tell One Person',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Message or tell one person you trust that you’re working on cutting back on vaping. Keep it as simple as one honest sentence.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How did it feel to say it out loud, 1 (uncomfortable) to 5 (relieving)?',
    },
  },
  {
    id: `${cid}_tools_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'tools',
    levelNumber: 18,
    order: 18,
    type: 'documentation',
    title: 'Tools Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You now have a hand substitute and some accountability in place.',
      fields: [
        { key: 'sticking', label: 'Which tool has stuck so far?', input: 'short_text' },
        { key: 'effectiveness', label: 'How much has it helped?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },

  // -------------------------------------------------------------- reflection
  {
    id: `${cid}_reflection_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 19,
    order: 19,
    type: 'documentation',
    title: 'How’s It Going, Really?',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'No pressure to be further along than you are — just be honest.',
      fields: [
        { key: 'progress_feeling', label: 'How do you feel about your progress?', input: 'scale_1_5' },
        { key: 'notes', label: 'What’s been hardest?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_reflection_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 20,
    order: 20,
    type: 'lesson',
    title: 'Withdrawal Is Temporary',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Irritability, restlessness, and trouble focusing are common when nicotine levels drop — they’re uncomfortable, but they’re your body recalibrating, not a sign something is wrong. These symptoms typically ease significantly within the first couple of weeks.',
      questions: [
        {
          prompt: 'What do irritability and restlessness usually mean when cutting back on nicotine?',
          options: ['Something is seriously wrong', 'Your body is recalibrating — a temporary, common process', 'You should immediately go back to vaping'],
          correctIndex: 1,
          feedbackCorrect: 'Right — these symptoms are a normal, temporary part of the process.',
          feedbackIncorrect: 'Not quite — these are common, temporary symptoms of your body adjusting.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 21,
    order: 21,
    type: 'exercise',
    title: 'Sit With the Discomfort',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'If you’re feeling irritable or restless right now, don’t try to fix it — just notice it in your body for the full timer, breathing slowly.',
      format: 'timed_reflection',
      durationSeconds: 90,
      completionPrompt: 'How does the feeling compare now to when you started noticing it?',
    },
  },
  {
    id: `${cid}_reflection_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 22,
    order: 22,
    type: 'lesson',
    title: 'A Slip Isn’t a Restart',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Most people who successfully cut back or quit don’t do it in a straight line — a slip after progress is common and doesn’t erase the progress you made. What matters is what you do in the next hour, not judging yourself for the slip itself.',
      questions: [
        {
          prompt: 'If you vape again after several smoke-free days, what does that mean?',
          options: ['All your progress is erased', 'It’s common, and doesn’t erase the progress you made', 'You should give up on cutting back'],
          correctIndex: 1,
          feedbackCorrect: 'Right — a slip doesn’t undo the progress that came before it.',
          feedbackIncorrect: 'Not quite — a slip is common and doesn’t erase what you’ve already built.',
        },
      ],
    },
  },
  {
    id: `${cid}_reflection_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 23,
    order: 23,
    type: 'exercise',
    title: 'A Quick Self-Compassion Break',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of a recent time you hit your vape without meaning to. Silently say to yourself: "This device was designed to be hard to put down — that’s not a personal failing. I can be kind to myself and keep going."',
      format: 'timed_reflection',
      durationSeconds: 60,
      completionPrompt: 'How does it feel to offer yourself that kindness, 1 (strange) to 5 (genuinely comforting)?',
    },
  },
  {
    id: `${cid}_reflection_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'reflection',
    levelNumber: 24,
    order: 24,
    type: 'documentation',
    title: 'Reflection Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'A brief look at how your relationship with vaping is shifting.',
      fields: [
        { key: 'self_kindness', label: 'How kind have you been to yourself this chapter?', input: 'scale_1_5' },
        { key: 'notes', label: 'Anything you want to remember from this chapter?', input: 'long_text' },
      ],
      shareableToCommunity: true,
    },
  },

  // ------------------------------------------------------------- maintenance
  {
    id: `${cid}_maintenance_01`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 25,
    order: 25,
    type: 'documentation',
    title: 'Where You Stand',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'Almost through the path — a check-in before we talk about keeping it up long-term.',
      fields: [
        { key: 'change_noticed', label: 'What’s actually changed since you started?', input: 'long_text' },
        { key: 'confidence', label: 'How confident do you feel keeping this up?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
  {
    id: `${cid}_maintenance_02`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 26,
    order: 26,
    type: 'lesson',
    title: 'Watch for High-Risk Moments',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Drinking alcohol and spending time with friends who vape are two of the most common relapse triggers, even after weeks of progress. Planning ahead for those specific situations — not just "trying hard" — is what tends to protect a streak.',
      questions: [
        {
          prompt: 'Which situation is a common relapse trigger, even after real progress?',
          options: ['Being alone at home reading', 'Drinking alcohol with friends who vape', 'Going for a walk'],
          correctIndex: 1,
          feedbackCorrect: 'Right — alcohol and vaping social circles are common relapse triggers.',
          feedbackIncorrect: 'Not quite — drinking and vaping social settings are the higher-risk moments here.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_03`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 27,
    order: 27,
    type: 'exercise',
    title: 'Plan Your Riskiest Moment',
    estimatedMinutes: 4,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Write down your single highest-risk situation for vaping, and one specific thing you’ll do differently the next time you’re in it.',
      format: 'real_world_task',
      durationSeconds: 90,
      completionPrompt: 'How ready do you feel to use this plan, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_04`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 28,
    order: 28,
    type: 'lesson',
    title: 'When to Get Real Support',
    estimatedMinutes: 4,
    xpReward: 20,
    creditReward: 1,
    content: {
      type: 'lesson',
      lessonText:
        'Evidence-based quitting usually combines counseling or behavioral support with the strategies you’ve built here — not willpower alone. If cravings still feel unmanageable after consistent effort, a doctor or cessation program can offer tools this app can’t.',
      questions: [
        {
          prompt: 'What does the evidence say works best for quitting nicotine long-term?',
          options: ['Willpower alone, without any other support', 'Counseling or behavioral support combined with self-directed strategies', 'Simply switching to a different vape device'],
          correctIndex: 1,
          feedbackCorrect: 'Right — combining support with self-directed tools tends to work best.',
          feedbackIncorrect: 'Actually, combining counseling/behavioral support with self-directed tools works better than either alone.',
        },
      ],
    },
  },
  {
    id: `${cid}_maintenance_05`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 29,
    order: 29,
    type: 'exercise',
    title: 'Name Your Support Person',
    estimatedMinutes: 3,
    xpReward: 25,
    creditReward: 1,
    content: {
      type: 'exercise',
      instruction: 'Think of one person you could message the next time you’re tempted to borrow a pod or buy a new device. You can add them as an emergency contact in the SOS section if it feels right.',
      format: 'real_world_task',
      durationSeconds: 60,
      completionPrompt: 'How comfortable would you feel reaching out to them, 1 to 5?',
    },
  },
  {
    id: `${cid}_maintenance_06`,
    trackId: 'addictions',
    categoryIds,
    chapter: 'maintenance',
    levelNumber: 30,
    order: 30,
    type: 'documentation',
    title: 'Path Complete: Final Check-In',
    estimatedMinutes: 3,
    xpReward: 15,
    creditReward: 1,
    content: {
      type: 'documentation',
      checkInPrompt: 'You made it through the whole path. Take a moment to look back.',
      fields: [
        { key: 'proudest_moment', label: 'What are you most proud of from this path?', input: 'long_text' },
        { key: 'current_mood', label: 'How are you feeling right now?', input: 'scale_1_5' },
      ],
      shareableToCommunity: true,
    },
  },
];
