// Must match `appGroupId` in targets/widget/MaxxWidget.swift and the
// entitlement generated by targets/widget/expo-target.config.js
// (`group.<ios.bundleIdentifier>.widget`). Update all three together if the
// bundle identifier ever changes.
export const APP_GROUP_ID = 'group.com.maxx.app.widget';
export const WIDGET_SNAPSHOT_KEY = 'maxx.widget.snapshot';
export const WIDGET_KIND = 'MaxxWidget';
